name: cryptkeeper
channels:
  - bioconda
dependencies:
  - python>=3.9
  - viennarna=2.4.18
  - ostir
  - transtermhp
  - pip
  - firefox
  - geckodriver
  - pip:
    - rhotermpredict
    - promotercalculator
    - selenium
    - bokeh
