# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-08 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptKeeperResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name=b'Name')),
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date')),
            ],
        ),
    ]
